name: 'SCUS-AlwaysOn-Infrastructure-Deployment'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - environments/scus/always_on.tf
    - environments/scus/main.tf
    - environments/scus/variables.tf
    - modules/**

parameters:
- name: environment
  displayName: Environment
  type: string
  default: prod
  values:
  - prod
  - staging

pool:
  vmImage: 'ubuntu-latest'

variables:
  region: 'South Central US'
  regionShort: 'scus'
  serviceConnection: 'azure-service-connection'
  tfStateResourceGroup: 'terraform-state-rg'
  tfStateStorageAccount: 'terraformstate'
  tfStateContainer: 'tfstate'

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: 'Validate'
    displayName: 'Validate Terraform'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.5.0'
    
    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/scus'
        backendServiceArm: '$(serviceConnection)'
        backendAzureRmResourceGroupName: '$(tfStateResourceGroup)'
        backendAzureRmStorageAccountName: '$(tfStateStorageAccount)'
        backendAzureRmContainerName: '$(tfStateContainer)'
        backendAzureRmKey: '${{parameters.environment}}-$(regionShort)-always-on.tfstate'
    
    - task: TerraformTaskV3@3
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/scus'

- stage: 'Deploy'
  displayName: 'Deploy Always-On Infrastructure'
  dependsOn: 'Build'
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy Infrastructure'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.5.0'
    
    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/scus'
        backendServiceArm: '$(serviceConnection)'
        backendAzureRmResourceGroupName: '$(tfStateResourceGroup)'
        backendAzureRmStorageAccountName: '$(tfStateStorageAccount)'
        backendAzureRmContainerName: '$(tfStateContainer)'
        backendAzureRmKey: '${{parameters.environment}}-$(regionShort)-always-on.tfstate'
    
    - task: TerraformTaskV3@3
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/scus'
        environmentServiceNameAzureRM: '$(serviceConnection)'
        commandOptions: '-var="environment=${{parameters.environment}}" -var="deploy_compute=false" -out=tfplan'
    
    - task: TerraformTaskV3@3
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/scus'
        environmentServiceNameAzureRM: '$(serviceConnection)'
        commandOptions: 'tfplan'